version: '3.5'

services:

  # Postgres DB
  db:
    container_name: tsri-db
    image: postgres:12.0-alpine
    ports:
      - 5432:5432
    volumes:
      - ../../../tsri-system/tsri-postgres/postgres_data_dev:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db

  # Django
  django:
    container_name: trsi-django
    build:
      context: ../../../tsri-system/tsri-django
      dockerfile: Dockerfile.dev
    ports:
      - "8090:8000"
    restart: always
    volumes:
      - static_volume:/app/assets/static
      - ../../../tsri-system/tsri-django/app:/app
    depends_on:
      - db
    env_file:
      - ./.env.dev

volumes:
  static_volume: