version: '3.5'

services:

  # Nginx
  t-nginx:
    container_name: trsi-nginx
    build:
      context: ../../../tsri-system/tsri-nginx/prod
    depends_on:
      - django
    volumes:
      - ../../../tsri-system/tsri-django/assets:/app/assets
    ports:
      - "8090:80"
    restart: always
    networks:
      - tsri-queueing

  # Postgres DB
  postgres-db:
    container_name: tsri-db
    image: postgres:12.0-alpine
    ports:
      - 5432
    volumes:
      - ./import-master-data.sql:/init/import-master-data.sql
      - ../../../tsri-system/tsri-postgres/postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db
    networks:
      - tsri-queueing

  # Django
  django:
    container_name: trsi-django
    build:
      context: ../../../tsri-system/tsri-django/trfai
    command: gunicorn trfai.wsgi:application --bind 0.0.0.0:8000
    restart: always
    depends_on:
      - postgres-db
    volumes:
      - ../../../tsri-system/tsri-django/assets:/app/assets
      - ../../../tsri-system/tsri-django/trfai/trfai_app/migrations:/app/trfai/trfai_app/migrations
      - ../../../tsri-system/tsri-django/trfai/templates/ldavis:/app/trfai/templates/ldavis
    env_file:
      - .env.prod
    networks:
      - tsri-queueing

networks:
  tsri-queueing:
    name: tsri-queueing