apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: tsri
  template:
    metadata:
      labels:
        component: tsri
    spec:
      securityContext:
        fsGroup: 2000
      containers:
      - name: tsri-django
        image: asia.gcr.io/tsri-268903/tsri-django
        resources:
            requests:
              cpu: "0.1"
              memory: "128Mi"
            limits:
              cpu: "0.3"
              memory: "256Mi"
        ports:
          - containerPort: 8000
        envFrom:
          - configMapRef:
              name: django-config
        env:
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: tsridbpassword
                key: SQL_PASSWORD
        volumeMounts:
          - name: django-storage
            mountPath: /app/assets
            subPath: assets
          - name: django-storage
            mountPath: /app/trfai/trfai_app/migrations
            subPath: migrations
          - name: django-storage
            mountPath: /app/trfai/templates/ldavis
            subPath: templates/ldavis
      - name: tsri-nginx
        image: asia.gcr.io/tsri-268903/tsri-nginx
        resources:
            requests:
              cpu: "0.1"
              memory: "128Mi"
            limits:
              cpu: "0.3"
              memory: "256Mi"
        ports:
          - containerPort: 5050
        volumeMounts:
          - name: django-storage
            mountPath: /app/assets
            subPath: assets
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.16
        resources:
            requests:
              cpu: "0.2"
              memory: "128Mi"
            limits:
              cpu: "0.3"
              memory: "512Mi"
        command: ["/cloud_sql_proxy",
                  "-instances=tsri-268903:asia-southeast1:tsri-db=tcp:5432",
                  # If running on a VPC, the Cloud SQL proxy can connect via Private IP. See:
                  # https://cloud.google.com/sql/docs/mysql/private-ip for more info.
                  "-ip_address_types=PRIVATE",
                  "-credential_file=/secrets/cloudsql/queueing-db-agent.json"]
        securityContext:
          runAsUser: 2  # non-root user
          allowPrivilegeEscalation: false
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
      imagePullSecrets:
        - name: gcr-json-key
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: django-storage
          persistentVolumeClaim:
            claimName: django-persistent-volume-claim