apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
      - name: queueing-frontend
        image: asia.gcr.io/tsri-268903/queueing-frontend
        resources:
            limits:
              cpu: "0.1"
              memory: "64Mi"
        ports:
          - containerPort: 3000
      imagePullSecrets:
        - name: gcr-json-key