apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: worker
  template:
    metadata:
      labels:
        component: worker
    spec:
      containers:
      - name: queueing-worker
        image: asia.gcr.io/tsri-268903/queueing-worker
        resources:
          requests:
            cpu: "200m"
            memory: "1024Mi"
          limits:
            cpu: "900m"
            memory: "2048Mi"
        env:
          - name: RABBITMQ_HOST
            value: rabbitmq-cluster-ip-service
          - name: RABBITMQ_PORT
            value: '5672'
          - name: EXPRESS_HOST
            value: express-cluster-ip-service
      imagePullSecrets:
        - name: gcr-json-key