apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: worker-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: worker-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: External
    external:
      metricName: "custom.googleapis.com|rabbitmq_queue_messages_ready"
      metricSelector:
        matchLabels:
          metric.labels.queue: processing.requests
      targetValue: 3