apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  DEGUG: "0"
  SECRET_KEY: "foo"
  DJANGO_ALLOWED_HOSTS: "localhost 127.0.0.1 [::1]"
  SQL_ENGINE: django.db.backends.postgresql_psycopg2
  SQL_DATABASE: trfai
  SQL_USER: trfaidb
  SQL_HOST: localhost
  SQL_PORT: '5432'
  DOMAIN_NAME: 'meawtsri.com'