version: '3.5'
services:

  ##############
  #--Frontend--#
  ##############

  frontend:
    container_name: queueing-frontend
    build:
      context: ../../../queueing-system/queueing-frontend
    networks: 
      - tsri-queueing

  ##############
  #-API System-#
  ##############

  # Nginx Reverse Proxy
  q-nginx:
    container_name: queueing-nginx
    build:
      context: ../../../queueing-system/queueing-nginx
    ports:
      - "8080:80"
    networks: 
      - tsri-queueing
    depends_on:
      - express
      - frontend
    restart: always

  # Express
  express:
    container_name: queueing-express
    build:
      context: ../../../queueing-system/queueing-express
    depends_on:
      - db
      - rabbitmq
    volumes:
      - ./database-config:/app/config
    networks: 
      - tsri-queueing
    env_file:
      - .env.prod    
  
  # Database
  db:
    container_name: queueing-db
    build:
      context: ../../../queueing-system/queueing-db
    restart: always
    volumes:
      - ../../../queueing-system/queueing-db/data-prod:/var/lib/mysql
    env_file:
      - .env.prod.db
    networks: 
      - tsri-queueing
  
  # RabbitMQ
  rabbitmq:
    container_name: queueing-rabbitmq
    image: rabbitmq:3.8.0-management-alpine
    hostname: rabbitmq
    env_file:
      - .env.prod.rabbitmq
    volumes:
      - ../../../queueing-system/queueing-rabbitmq:/var/lib/rabbitmq
    networks: 
      - tsri-queueing

  # Redis
  redis:
    container_name: queueing-redis
    image: "redis:alpine"
    networks:
      - tsri-queueing
  
  ##############
  #---Worker---#
  ##############

  worker:
    build:
      context: ../../../queueing-system/queueing-worker
    volumes:
      - ../../../queueing-system/queueing-worker/documents:/app/documents
      - ../../../queueing-system/queueing-worker/converted:/app/converted
      - ../../../queueing-system/queueing-worker/results:/app/results
    restart: always
    networks: 
      - tsri-queueing

networks:
  tsri-queueing:
    name: tsri-queueing
