apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: rabbitmq
  template:
    metadata:
      labels:
        component: rabbitmq
    spec:
      volumes:
        - name: rabbitmq-storage
          persistentVolumeClaim:
            claimName: rabbitmq-persistent-volume-claim
      containers:
      - name: queueing-rabbitmq
        image: rabbitmq:3.8.0-management-alpine
        resources:
          requests:
            cpu: "0.1"
            memory: "256Mi"
          limits:
            cpu: "0.1"
            memory: "256Mi"
        env:
          - name: RABBITMQ_DEFAULT_USER
            value: ml-rabbitmq
          - name: RABBITMQ_DEFAULT_PASS
            valueFrom:
              secretKeyRef:
                name: rabbitmqdefaultpassword
                key: RABBITMQ_DEFAULT_PASS
        volumeMounts:
          - name: rabbitmq-storage
            mountPath: /var/lib/rabbitmq
            subPath: rabbitmq
        ports:
          - containerPort: 5672
          - containerPort: 15672